### ISSUE TITLE
Have more meta_tags

### ISSUE THREAD

**Issue by Benefit-Zebra** [efroemling/ballistica#104]
I think we should add more meta tags. Like if I want to explicitly add new powerups or new bombs to game, using _snowypowerup method_. I will introduce that meta_tag which will make the **script to run at the launch of the game.**

snowypowerup method:

```python
---snippet---
from bastd.actor import powerupbox
from bastd.actor.powerupbox import _TouchMessage, PowerupBoxFactory, PowerupBox

class NewPowerupBoxFactory:
    ---snippet---

class NewPowerupBox:
    ---snippet---

powerupbox.PowerupBoxFactory = NewPowerupBoxFactory
powerupbox.PowerupBox = NewPowerupBox
```

**Comment by EternalARK** [comment]
Eric should definitely put this on the schedule.

**Comment by efroemling** [comment]
Yes this something I'm planning. It will probably happen in [1.8](https://github.com/efroemling/ballistica/wiki/Roadmap#ballistica-18) since there'll be a lot of code refactoring to split out the existing bombs/powerups into their own nice clean modules.

Basically powerups and bombs should look a lot more like minigames do now; each in their own module with a metatag so that the game can find them.

It'll be interesting to play around with ideas such as letting the user customize which powerups are available per game, etc.

The one meta-tag thing that I'm planning to do now (in 1.5.x) is some sort of general purpose 'Plugin' tag which will let users run arbitrary code at game launch or other times. That should help make up for the fact that stuff in the mods dir no longer gets auto-imported at launch...

**Comment by efroemling** [comment]
As a heads-up: in the new 1.5.23 builds I just added the concept of [Plugins](https://github.com/efroemling/ballistica/wiki/Knowledge-Nuggets#hello-world-2-creating-a-new-plugin).

Defining a plugin lets you run code at specific times in the app lifecycle. Right now the only one is 'on-launch' but we can add to this with whatever would be useful. All detected plugins can be enabled/disabled by the user via GUI in settings->advanced->plugins.

Let me know if you have any thoughts...

**Comment by efroemling** [comment]
Hey folks; I'm gonna close this for now. I do intent to add more meta-tags over the next few versions for adding things such as maps and powerups without having to modify game code. Aside from that, I can add more callback functions to the ba.Powerup class for people who want to have their code run at specific times in the game. Please open issues for any individual such requests/thoughts...
