### ISSUE TITLE
My advanced fly3d mod cann't works after optimization controls 

### ISSUE THREAD

**Issue by DrovGamedev** [efroemling/ballistica#118]
In update 1.5, controller data is not passed to the on_move_up_down and on_move_left_right methods if Spaz is suspended above the ground

**Comment by efroemling** [comment]
Hmm I don't think anything in the C++ layer would have changed to prevent these events  from making their way to the Python layer. Otherwise I think the existing flying maps such as happy-thoughts would be broken too, right? Are you sure you are seeing this correctly? And if so, can you give me steps to reproduce the problem?

**Comment by DrovGamedev** [comment]
my bad
