### ISSUE TITLE
CHANGE ID

### ISSUE THREAD

**Issue by PuneetGurjar** [efroemling/ballistica#126]
Can we change the name of the default profile in PC [PC10089] and Android[android13878172] like we can change name of google play id

**Comment by PuneetGurjar** [comment]
I tried to change name through config.json file in PC. The name was changed but whenever I come online it changes to default 😥

**Comment by Benefit-Zebra** [comment]
> Can we change the name of the default profile in PC [PC10089] and Android[android13878172] like we can change name of google play id

When you connect to internet, the master server allots your device id a unique name eg:[PC10089] and Android[android13878172]. So everytime you connect to internet, even if you change the PC or Android config, the ID of device remains same and you get your default name.

**Comment by Benefit-Zebra** [comment]
> Can we change the name of the default profile in PC [PC10089] and Android[android13878172] like we can change name of google play id

When you _connect to internet_, the master server allots your **device id** a **_unique name_** eg:[PC10089], Android[android13878172]. So **everytime you connect to internet**, even _if you change the PC or Android config_, the **_ID of device remains same_** and you get your default unique name. 

Your **unique name can only change** when you _erase data/reset/format your device_, since Device ID changes. You cannot change the unique name according to your wish.

**Comment by efroemling** [comment]
I've got plans to add a customizable globally-unique account name which should solve this problem. Hopefully I can finish that soon.
