### ISSUE TITLE
No Impact blast when Hit owner

### ISSUE THREAD

**Issue by Benefit-Zebra** [efroemling/ballistica#129]
When we throw a impact bomb, and it touches us(owner), it does not explode. It does cause damage when the spaz is inside the range of Impact bomb when it touches ground and explodes. Here is the [video](https://drive.google.com/file/d/1-MYN5PSgP7wRi747w7KD36Hi7_T4ZDOb/view?usp=drivesdk) for better understanding.

**Comment by PuneetGurjar** [comment]
It also happen when your team mate is very near to you and if you enemy kills and grab your bomb then also it fuse after 2-3 seconds.
This is not a problem but a good thing for the owner and also it doesn't blast because there is no gap between bomb and body or you can say it's fuse time with owner after grab again is little bit more.

**Comment by PuneetGurjar** [comment]
I hope you understand that this is good thing 👍

**Comment by astrojade** [comment]
Okay, See some stuff are understandable, but what about the bots which just spawn, and pull out an impact? The bomb just gets deflected if another bomb  like an impact is on the head, its annoying.  i dont have the video regarding it, or id post it.

**Comment by efroemling** [comment]
This is very much intentional. Without that bit of code, if you pull out an impact bomb and then jump you tend to blow your own head off.
Perhaps there could be some smarter way to handle this such as switching the bomb behavior to allow self-impacts only *after* the throw, but I'd prefer to avoid complicating the logic at least for now. For 1.8 I plan to separate all bombs/powerups into their own classes and that might be a good time to revisit bomb logic to make it smarter.
