### ISSUE TITLE
False Tournament Modification Bug

### ISSUE THREAD

**Issue by PythonCode-blip** [efroemling/ballistica#133]
So when I complete/lose a tournament, I get this, and no I did not edit any code in the game and still get this error from a linked account, even if I unlink that account I don't think this can be undone, please help.
![Screenshot_2020-07-27-21-52-04](https://user-images.githubusercontent.com/66983599/88622961-b45e4d80-d058-11ea-8ab9-14b972705c0e.png)

**Comment by PythonCode-blip** [comment]
I don't know how this happened too.

**Comment by efroemling** [comment]
Which version/platform of the game is this? Can you try a fresh install and see if it still occurs? This will happen if the game detects any added/modified files or if python commands have been run via the console or telnet.

**Comment by astrojade** [comment]
Have you added any files in the mod pack folder @PythonCode-blip ? Copy paste these files in another folder as backup and, delete those mods in the mod folder. Then try playing the game, The tournament games should work.  Eric can you please do something about this, technically modfiles which affect the online server or stuff, which is not related to the tournaments is getting counted as modification for tournaments.

**Comment by efroemling** [comment]
Yes if you have added anything in your mods folder, even if it is not being used, the game will consider itself to be modified and you will get this.
Is that the case for you?
That issue is being discussed in general in #149 so I'll close this now; please re-open if this if you are certain there is nothing in your mods folder/etc.
