### ISSUE TITLE
Can you please make a kick vote log system?

### ISSUE THREAD

**Issue by Akshay-Y7** [efroemling/ballistica#135]
People just try to kick others because others play better than them, or they just wanna kick others without any reason! Using python's open() function you can make a text file in which the details of the kick vote are written.

**Comment by efroemling** [comment]
My plans for one of the upcoming version (likely [1.8](https://github.com/efroemling/ballistica/wiki/Roadmap#ballistica-18) but possibly sooner) includes moving the entire kick system to the scripting layer so things like this will be easy to do. I don't want to add features such as this now because I would have to implement them in C++ and then re-implement them in Python soon. I'll keep this open as a reminder though

**Comment by Dliwk** [comment]
Let's leave just one issue about improving the kick-voting system: #41
