### ISSUE TITLE
Add a other languages for internal keyboard please

### ISSUE THREAD

**Issue by KoLenka12** [efroemling/ballistica#137]
For example: Arabic, Russian, Spanish, etc.

**Comment by Benefit-Zebra** [comment]
Adding other languages to Internal Game Keyboard will not be ideal since these languages do have extra symbols which will cause the layout go out of space. So the layout will have to be reformatted for each language. Also not all languages are able to be displayed on all devices.

But the decision of doing it depends on @efroemling.

**Comment by Dliwk** [comment]
Hmm, maybe not bad idea might be some API for adding internal keyboard language? And who want may just use mod what support his language. For example:

```python
# ba_meta export keyboard
class RussianKeyboard(ba.Keyboard):
    pages = [[
        ('й', 'ц', 'у', 'к', 'е', 'н', 'г', 'ш', 'щ', 'з', 'х', 'ъ'),
        ('ф', 'ы', 'в', 'а', 'п', 'р', 'о', 'л', 'д', 'ж', 'э'),
        ('я', 'ч', 'с', 'м', 'и', 'т', 'ь', 'б', 'ю')
    ]]
```

It should support many languages...

**Comment by Dliwk** [comment]
Closing now; simple [keymap-creating API][wiki] is available, so it's easy to create your own.

[wiki]: https://github.com/efroemling/ballistica/wiki/Knowledge-Nuggets#hello-world-3-creating-a-new-keyboard
