### ISSUE TITLE
Android version does not handle active call

### ISSUE THREAD

**Issue by EternalARK** [efroemling/ballistica#143]
In the replay window, double click can trigger active call and start the replay.
But this won't work on android release. It's a bug I think.

**Comment by efroemling** [comment]
Ok this should be fixed in f4a547f65eacf8e4de510c118e1e21bb4d5b8b3c
Basically, on mobile, scroll-widgets have to intercept clicks in order to (potentially) perform scrolling, and they were not properly passing the click count on to their children.
Let me know if this seems to be behaving for you now and we can close this.

**Comment by efroemling** [comment]
Gonna close this now as it should be fixed. Holler if you still see it anywhere.
