### ISSUE TITLE
Light Node not deleted

### ISSUE THREAD

**Issue by Benefit-Zebra** [efroemling/ballistica#163]
In minigame Chosen One, if the player is the Chosen One and he quits/leave game, his light node remains blinking.

[Light Node Video](https://drive.google.com/file/d/18z0JmUNOINr3EwLwQjuCxvmnvpl_jmqV/view?usp=drivesdk)

I think this is because when we leave game, it doesn't send a PlayerDeathMessage (so I assume). Since light node is a NodeActor, it should be deleted when the player dies, but in this case it doesn't happen.

We should delete this node if the chosen one leaves or dies.

**Comment by efroemling** [comment]
Thanks for the heads up. There was some logic in on_player_leave() which was supposed to clear any chosen-one state (including the light actor) but it relied on the player being in the game's self.players list, and they are actually removed from that list before on_player_leave() is called so it wasn't working. Should be fixed in b0907652e63fb247866e1817466d2b551669b932
