### ISSUE TITLE
Unshatter not working properly

### ISSUE THREAD

**Issue by Benefit-Zebra** [efroemling/ballistica#168]
In below video, a player shatters and after it, it unshatters. When the player unshatters, the legs remain unattached and look like zombie legs.

But when we freeze during this state, the legs get attach again. 

[Shatter Video](https://drive.google.com/file/d/1C2LIeZkATxzVy0AUmtgwPRzhWOkAKyvF/view?usp=drivesdk)

**Comment by efroemling** [comment]
Interesting. Was that custom code to make the guy shatter as he passed the flag? And was this a local game or a network game?

**Comment by Benefit-Zebra** [comment]
It was a local game.

When the player touches flag, 
To Shatter:
```python
    player.actor.shattered = True
    player.actor.node.shattered = 1
```
To Unshatter:
```python
    player.actor.shattered = False
    player.actor.node.shattered = 0
```

**Comment by efroemling** [comment]
Oh ok. In that case, I would call this the expected behavior. Shattering wasn't intended to be undoable, so that behavior is undefined. I hope to get the low-level c++ code open-sourced soon-ish and then it will be possible to clean up this behavior if desired, but it's not something I can spend time on myself right now.
