### ISSUE TITLE
Sooner update

### ISSUE THREAD

**Issue by YairMejiaValtierra** [efroemling/ballistica#181]
Eric bro update the game sooner people in the servers of Asia are spiking down because the game has not been updated yet and make 1.5 hosting a little easier and you need to be compatible with 1.5 because 1.4 may no longer be compatible with 1.5 and need to play on those servers with 1.5 (sorry my English bad)

**Comment by astrojade** [comment]
Yea But we cant do anything but wait. I mean once bs 2.0 comes out all old and new players will come back to play BombSquad. The only thing we can do at this point is wait. There are glitches like the teleportation, but there is nothing much we  can do about it, since i think eric said that, this will be considered as normal for future updates. Or am i wrong?

**Comment by Dliwk** [comment]
Hey, 1.4 and 1.5 are network-compatible versions.
