### ISSUE TITLE
Hosting BombSquad - Connection failed while connecting trough public servers list

### ISSUE THREAD

**Issue by realSamy** [efroemling/ballistica#189]
I ran latest version (1.5.26) on Ubuntu 20.04 vps, No problem when connecting manually, but I can't connect to my server under public parties list (Connection failed.) and it's name in list is gray, what should I do to fix it?

**Comment by SushrutShidhaye** [comment]
Did u forwarded port to 43210?

**Comment by realSamy** [comment]
when I tried it on iptables I got error about "my server is not joinable on internet", seems I don't know how to do it correctly! may you help me on that?

**Comment by SushrutShidhaye** [comment]
Which host u r using?

**Comment by realSamy** [comment]
I have Hetzner Ubuntu 20.04 cloud vps and tried https://files.ballistica.net/bombsquad/builds/BombSquad_Server_Linux_1.5.26.tar.gz

**Comment by SushrutShidhaye** [comment]
Oh sry i did read properly

Well chng ur security group details
 
Or open new 
In configure Security Settings:-
Type:- All traffic
Source:- Anywhere

*Dont change any other things*

**Comment by realSamy** [comment]
unfortunately I'm not very familiar with linux commands, may you send commands I should use, please?

**Comment by SushrutShidhaye** [comment]
Umm same here😁
But try searching on internet 
About Port forwarding....

I dont know more about any other web services....

**Comment by realSamy** [comment]
I tried before
> when I tried it on iptables I got error about "my server is not joinable on internet",

**Comment by realSamy** [comment]
I tried before 


> when I tried it on iptables I got error about "my server is not joinable on internet", seems I don't know how to do it correctly! may you help me on that?

**Comment by N-a-h** [comment]
allow 43210 UDP port in hetzners firewall(look it up online)
and run ufw allow 43210/udp in ssh console

**Comment by astrojade** [comment]
Okay I am assuming that you're port forwarding. Correct me if i am wrong.
Regarding port forwarding, you need to make sure that the 43210 is connectable to the internet. To do this, you need to go into your router settings and head to the port forwarding tab, where you need to type in your systems details plus the ip through which you   willl be allowing others to access ur network. I am not aware of the entire details regarding how the port forwarding works ie in which kind of networks, but you just need to make sure you have added the correct details in your router page before checking the game whether its accessable or not. It doesnt work in all networks, If you're not able to allow access to this particular port from your side then you need to contact your isp to inform him to open this port so you can let others access ur network. They will talk about static ip gibberish but you just need to tell them its okay if u dont have a static ip. Because my ip changes all the time, I need to reinput a new one everytime i start the server.
On my system port forwarding works, and i had to add the details in 2 3 tabs for it to work. And once it works, The NO word will change to YES ingame, if it doesn't work, just try hitting connect and see whether it changes or not. There tends to be a glitch sometimes with the manual page.  I hope this helped.
