### ISSUE TITLE
Is it possible for this game to use directx 11 instead of ogl?

### ISSUE THREAD

**Issue by astrojade** [efroemling/ballistica#192]
My system is a a low end cpu, and because of this, i experience a shift in frames while playing, this causes the inputs to get delayed when the frame falls at specific intervals. I noticed that for other games, this doesnt seem to happen alot. Maybe it could be the lag, or just my system itself. Does anyone else have this problem? I have enabled vertical sync, it has reduced the extent of the frame stutttering but it gets annoying when the frames feel like they are moving slightly to the left and right.

**Comment by efroemling** [comment]
I would love for the game to support DirectX or other graphics APIs such as Metal, Vulkan, etc. Perhaps that would help whatever the performance issue is that you're seeing. Unfortunately it is a custom engine so adding those will take a bit of work. I did, however, design the engine in a way where that will hopefully be possible. I've been open-sourcing most of the low level code recently (including the [graphics engine](https://github.com/efroemling/ballistica/tree/master/src/ballistica/graphics)) and hope to do a bit of cleanup on it so that such a port will not be difficult for either me or someone else to tackle.

**Comment by lemonyPRIDE** [comment]
@efroemling it maybe a stupid query but say suppose I take your permission _(just a thought and idea I dunno how to use it)_ and port this game through a different game engine for example say, **UNREAL ENGINE** , will it increase your games performance as unreal engine supports DirectX ?

**Comment by astrojade** [comment]
So i managed to fix the problem for this system. Really annoying. No idea again what fixed it. The only thing i know is that the quality settings in the nvidia control panel doesnt seem to adjust for any game i am playing on this system. So by setting it back to performance helped in reducing the stuttering while gaming, otherwise i couldnt even reduce the stuttering even while i was playing on 800x600 resolution. 
The only thing left to do is learn more regarding all those settings stuff in nvidia control panel and see what is wrong with my 920m card. Yes outdated card, that is the only reason why its giving me heaps of trouble. Very sorry for giving you headache, it was a fault from my side, and i clearly couldnt understand it. Sorry.
