### ISSUE TITLE
BombSquad on PC Acts as a malware

### ISSUE THREAD

**Issue by YairMejiaValtierra** [efroemling/ballistica#195]
so basicaly my aanti virus protection said that bombsquad.exe app is a extreme virus and that is a premium anti virus now my big brother wont let me play bombsquad ever again pls help Mr. Froemling

**Comment by efroemling** [comment]
Hmm I'm really not sure why the game would be mis-identified as a virus. It is definitely not one 🤔. I wish there was something I could do to help here, but I'm not sure what that would be.

**Comment by TornadoesPride** [comment]
If he installed mods or downloaded from a 3rd party source that would a possible explaination. But if an actual virus did copy and replicate itself as bombsquad so that the user opens it, even if unintentionally, the anti virus may have detected the actual virus NOT the game itself. Happened to me with softwares a lot of times back in the day. I suggest @YairMejiaValtierra you tell your brother to scan the actual folder of bombsquad and reason with him, even if your game is not a virus download a fresh copy of Bombsquad from https://files.ballistica.net/bombsquad/builds/

Hope that helps 👍

**Comment by Dliwk** [comment]
Haha I remembered as my first helloworld.exe antivirus detected as a malware :smile:

**Comment by 7wells** [comment]
@efroemling 

Hi Eric, I hope my message finds you well! :smiley:

Various virus scanners identify the executable `BombSquad.exe` in your official build 1.6.5 from [there](https://files.ballistica.net/bombsquad/builds/BombSquad_Windows_1.6.5.zip) as malicious:

https://www.virustotal.com/gui/file/adb8ac26349eda58326a8c6c206443be0c543fcc1ab14ed6d65a8d2d5d1b02e9

![grafik](https://user-images.githubusercontent.com/65889763/147228463-689fd659-6325-45b3-a91d-2a6c0377f98e.png)

This was a confirmation of my initial finding with IObit Malware Fighter 9.

Is this a false positive? And/or related to a problem with Visual Studio? (see hints [there](https://developercommunity.visualstudio.com/search?space=8&q=Fugrafa))

Would you mind checking if someone hacked your site and manipulated your files? Furthermore, could you please consider adding checksums (MD5, SHA, whatever) in a safe place (e.g., here on GitHub in addition to the download site?) for verification that the files have not been tampered with? Thank you so much!

I wish you and everybody peaceful Christmas Holidays, and most of all, good health and all the best for 2022! :four_leaf_clover:

**Comment by Dliwk** [comment]
Let's move it to #413
