### ISSUE TITLE
Bug - Forwarding my UDP port 43210 to my local address is not working

### ISSUE THREAD

**Issue by bel1808** [efroemling/ballistica#206]
## Description
I followed all the steps on my router, I now have a virtual server set in the following way:

Internal IP Address | LAN Port | WAN Port | Protocol
192.168.0.108 | 43210-43210 | 43210-43210 | UDP

I already closed my browser and bombsquad and opened them again, but when I go to gather>Manual>Show my Address , it still says I'm not joinable from the internet.

What else can I do?

## Expected behavior
After following these steps I should be able to gain access to join from the internet.

## Machine
**Platform**: Windows 10
**BombSquad version**: [1.5.27]

## Screenshots
Put some screenshots here if needed.
![image](https://user-images.githubusercontent.com/74074774/98412283-48b75380-203d-11eb-8947-5b7296301a92.png)
![image](https://user-images.githubusercontent.com/74074774/98412317-510f8e80-203d-11eb-899d-7a7137438b26.png)

## Extra
Please feel free to contact me at bel.aguilar18@gmail.com if you need additional information, thanks a lot!

**Comment by bel1808** [comment]
@efroemling @Dliwk could you please help me with this? Thank you!!

**Comment by Dliwk** [comment]
Have you checked the Windows firewall?

**Comment by bel1808** [comment]
Yeah I gave access to all bombsquad aplications, is there anything else I should grant access to? 
![image](https://user-images.githubusercontent.com/74074774/98417056-dd25b400-2045-11eb-96d1-9eef0863d93b.png)

**Comment by Dliwk** [comment]
Hmm this may be a problem on the side of your provider; they may simply not provide the ability to connect directly to your IP.

**Comment by astrojade** [comment]
Well in mine i had to go through multiple pages and see whether i can add the 43210 port there, i can send you the pics, but i dont know if it will be of much help to you. After i changed my settings in the router, it would still continue to display the word 'No' for the statement "Are you joinable from the internet" but if i connect to another server and then exit the server, then the 'No' statement would change to 'Yes'. It was a bit confusing at first but yes, it occurs like that for me. I think this keeps happening to me because i have set one particular ip in the router settings, when my ip address keeps changing
 every day.
![image](https://user-images.githubusercontent.com/67503088/99902256-685ba680-2ce2-11eb-932a-eef77af9221d.png)
![image](https://user-images.githubusercontent.com/67503088/99902451-f5532f80-2ce3-11eb-8e36-e4586bd4a703.png)

If it is still not working for you, then contact your service provider and ask him whether they can enable the port forwarding for your game. Also tell them that you do not need a static ip address, because mine seems to be working fine, even though the ip keeps changing everyday. I just need to go back into the router settings and change the ip address and I Am Done! It will Connect! OR i just enter a server, leave it and it will display as Yes for a particular time period. So until that time period comes to an end, i can let everyone join.
