### ISSUE TITLE
Some troubles with servers

### ISSUE THREAD

**Issue by DrovGamedev** [efroemling/ballistica#208]
Only 10 of 16 server is seeable in server-list of game.
How can I make all of my servers seeable

**Comment by efroemling** [comment]
Are all of these servers on the same IP address? The master server has a max-servers-per-ip setting because someone was spamming the list with hundreds of dummy servers running on one machine. But if you've got actual valid servers not showing up then I can raise the limit or whitelist your servers..

**Comment by DrovGamedev** [comment]
This is what I need, Thank you

**Comment by efroemling** [comment]
So do you need me to raise the limit? Or can you put some of them on another IP address?

**Comment by DrovGamedev** [comment]
I can't, all servers are linked by a database located on the vm
