### ISSUE TITLE
bombsquad fails to run on Arch Linux due to hard reliance on Python 3.8

### ISSUE THREAD

**Issue by cipherize** [efroemling/ballistica#214]
See the title. Arch Linux tracks the latest stable, which is now Python 3.9. Not sure how much effort would be required to support newer Python versions.

**Comment by ritiek** [comment]
You can install [Python 3.8 from AUR](https://aur.archlinux.org/packages/python38/). I don't think it's realistic that bombsquad Python version and official Arch package for Python should always remain in sync.

**Comment by cipherize** [comment]
I somehow missed that that was available. I'll have the PKGBUILD maintainer update the dependency. Thanks!

**Comment by efroemling** [comment]
As an FYI: my plan is to keep the game synced with the version of Python shipping in the latest Ubuntu LTS releases, since that keeps things simplest for me when setting up servers/etc. Currently that's 3.8. It might be trivial to get current builds running under 3.9 (perhaps just a creative symlink) but I haven't tried.
