### ISSUE TITLE
Suggestion: Use a default config separately

### ISSUE THREAD

**Issue by mzfr** [efroemling/ballistica#24]
I was looking in this code and I noticed that you are using a similar approach in the server.py as in the existing version of the game i.e there is a function that sets the default config values.

But I would suggest that we decide a specific format may be JSON or yaml for having a config file and then write a config parser which would be responsible for using values from the custom config file and will use existing default config for all the values which are not present in the custom file.

Currently, this is done in `.py` files but if we go down my suggested path then it would be better since the code in the server.py would be much cleaner and other users will be able to modify the config without having to touch the code files.

Let me know what are your thoughts on this, if you'll be okay with this change then I'll be happy to make PR for it.

**Comment by mzfr** [comment]
Another thing this would do is we can ask the users to make a custom config file with say `config.dist` or something similar name and have that name already added in our `.gitignore` file this way if a user creates a new custom config file that wouldn't show up in their `git diff`.

**Comment by efroemling** [comment]
Yes I would definitely like to rethink the server setup a bit since now is a good opportunity to do so. As a first step, I'll try to get 'prefab' build targets added soon for the headless versions of the game so we can start trying stuff.

Both of your ideas sound good to me. My vote would be .yaml for the config format since that way we can include comments in sample configs. I plan to replace the raw config dict being used by server.py with a dataclass type shared between server.py and the game scripts (so that the type-checker will help us keep everything in sync) and then we can just override the config instance's defaults with whatever is in the user config.

I also like the idea of something like a config.dist.yaml and pre-arranged .gitignore'd config.yaml so server-owners can just clone the repo and pull latest changes occasionally without having to recreate configs...

I'll try to get those prefab builds up soon...

**Comment by efroemling** [comment]
So I went ahead and did a pretty substantial re-architecting of the server manager setup and incorporated some of these ideas. The server manager script now looks for a config.yaml file, and the build generates a config_template.yaml which can be copied as a starting point (and this is all in the build directory which is not git managed anyway, so no need to add anything to .gitignore). The template version is auto-generated with commented out entries/descriptions for all values available in the ServerConfig Python dataclass.

Let me know if you have any thoughts on things; hopefully this new setup will be much easier to expand on... (and I'll go ahead and close this now)
