### ISSUE TITLE
Add emojis

### ISSUE THREAD

**Issue by Al-Clouds** [efroemling/ballistica#296]
Have you planned to add a system for adding more emojis in the game without modify your core game. Or we need to make tricks to add them?

**Comment by Dliwk** [comment]
Hmm; if you running Android version you should already be able to use emojis. Are you talking about these standard emojis on other platforms?

**Comment by efroemling** [comment]
I'm guessing you are referring to the stuff in the fontExtras* textures? These are custom characters specific to the game that make use of the [Unicode Private Use Areas](https://en.wikipedia.org/wiki/Private_Use_Areas).

I think these will always have to be tied to the core game. The problem is that they can show up in chat messages or public game names or anywhere else text can be displayed, so allowing modding them would cause things to show up incorrectly for most players who don't have the mod.

Though I'm open to adding icons if people have specific requests that seem like they'd be generally useful..

**Comment by Al-Clouds** [comment]
Ok it's exactly what i'm talking about.
Thanks for the fast answer
