### ISSUE TITLE
Error: got remote character not in their character list...

### ISSUE THREAD

**Issue by Awesome-Logic** [efroemling/ballistica#30]
![image](https://user-images.githubusercontent.com/36323763/80958467-b54d5d80-8e22-11ea-9ad0-5f55b9a7c5be.png)

I just hosted a BS 1.5 Server.
It happened in 'Race'. This is not intended right?

**Comment by efroemling** [comment]
Hmmm; possibly not, though that should be a harmless error. I'll look into it.
Were you playing with people you know? And if so, do you know if any of them are running hacks? (to unlock characters locally or anything like that?)

**Comment by Dliwk** [comment]
I have same logs. Clients haven't any hacks, this line shows after anyone join as non-spaz; client version doesn't matter (1.4 or 1.5).

**Comment by efroemling** [comment]
Ok I dug into this more. It turns out that is reporting a condition that is currently expected. I had added that warning with the intention of fixing the underlying condition, but it is not high priority so for now I've cleared out the print statement and will close this bug. Thanks for the heads up.
