### ISSUE TITLE
Petition to make a Discord server

### ISSUE THREAD

**Issue by joebyjo** [efroemling/ballistica#359]
hopefully it will get the community to engage more with each other thanks to Instant Messaging. It can feature help channels that help beginners working with APIs and Ballistica with quick responses. Maybe it can even include a channel where people can post their plugins,mods,ideas etc.

**Comment by Dliwk** [comment]
I'll probably quote here @efroemling answer from [here][1]
> I agree it would be a good thing, and I've gotten asked about that a lot. I'm just often in heads-down mode so I worry it would suffer from a lack of moderation/attention on my part. Though perhaps I could wrangle some volunteer moderators/organizers to help out...

I think Discord server will be nice improvement to our community, at least because this is better place for some 'stupid' questions, not bugs/feature requests what have to be tracked or some complex questions (for which this GitHub repo is better suited).

Furthermore, as partially mentioned, people will post some their handworks and communicate with each other more active and faster.

And this 'official' server (like this repo) will help centralize community. This is all just theoretical reflections, and we still need some @efroemling  note about that.

[1]: https://github.com/efroemling/ballistica/discussions/219#discussioncomment-286482

**Comment by efroemling** [comment]
Ok, how about if I promise to start up an 'official' discord server first thing after 1.7 is done? 😬
As long as some of you active community members don't mind helping with moderation...

I was thinking it could provide a nice opportunity to schedule a weekly 'developer hour' or something where people could ask tech questions or we could all chat about modding or other ideas. I could try to at least always be there for that. Though I wonder what time would work best for everyone considering we're all spread throughout the planet 🤔

**Comment by vishal332008** [comment]
> Ok, how about if I promise to start up an 'official' discord server first thing after 1.7 is done? 😬 As long as some of you active community members don't mind helping with moderation...
> 
> I was thinking it could provide a nice opportunity to schedule a weekly 'developer hour' or something where people could ask tech questions or we could all chat about modding or other ideas. I could try to at least always be there for that. Though I wonder what time would work best for everyone considering we're all spread throughout the planet 🤔

As 1.7 is finally released , i was thinking that maybe this "discussion" about making a discord server can be solved.

And there are many people including @Dliwk , @imayushsaini and many other contributors ready in bombsquad communities such as
BCS  -  https://discord.gg/ucyaesh 
BombSpot  -  https://discord.gg/zcwncqYDur 

to help you in the server moderation.

**Comment by EraOSBeta** [comment]
> Ok, how about if I promise to start up an 'official' discord server first thing after 1.7 is done? 😬 As long as some of you active community members don't mind helping with moderation...
> 
> I was thinking it could provide a nice opportunity to schedule a weekly 'developer hour' or something where people could ask tech questions or we could all chat about modding or other ideas. I could try to at least always be there for that. Though I wonder what time would work best for everyone considering we're all spread throughout the planet 🤔

I'm up for moderation! Also idk why but i think Saturday 16:30 GMT would be a good time for a weekly dev hour

**Comment by efroemling** [comment]
Hey folks!
Hate to be pedantic, but I'm not *quite* considering 1.7 released yet. First test builds are out on ballistica.net, but there are a few things I still need to finish up:
- I need to enable the new workspaces feature for V2 accounts. (which is important because otherwise it becomes a lot harder for Android people to mod stuff in 1.7 due to increased OS security). It will provide a nice benefit to anyone using a V2 account 😬
- I need to push 1.7 out to Google Play. This will be a pretty huge stress test of all the new V2 server stuff (the game still talks to V2 servers even if you're not technically logged in with a V2 account) so I want to tread carefully.
- Any other bugs that pop up as people are testing 1.7

That being said, those aren't huge tasks, so it won't be too much longer. I apologize for making everyone wait so long for 1.7 in general, but I'm really excited about what the new server stuff will enable and I think it'll be worth it. And I promise the Discord server will be the very next thing on my todo list!!

**Comment by efroemling** [comment]
Ok, 1.7 is mostly in a stable state, so as promised:
https://discord.gg/P5cczREa

Hop on and say hi or let me know any thoughts about how we want to set the server up. I haven't hosted a discord server before so I'll definitely be leaning on you folks for ideas/moderation help/etc.

**Comment by 3alTemp** [comment]
![mb](https://github.com/efroemling/ballistica/assets/79161340/aed7f621-bc36-4950-a994-91bb770ebbdc)
