### ISSUE TITLE
Bug of Arabic language in PC (Windows Version) Bombsquad

### ISSUE THREAD

**Issue by krahma9990** [efroemling/ballistica#367]
### Thanks to Mr. Eric and the entire Ballistica community.

![Screenshot_512](https://user-images.githubusercontent.com/42889595/156680517-fd8c8218-7121-41b1-b41d-fb8ba14013cc.png)

**Comment by efroemling** [comment]
Yes, this is a known issue. It is high on my to-do list of things to fix before releasing an 'official' PC version (on Steam or wherever). Currently all versions of the game can display a limited set of characters (the ones included in the game's bundled textures) but to display the entire unicode range requires talking to the OS to have it render text itself. I've wired this up on Mac and Android but still need to do so for Windows and Linux.

**Comment by krahma9990** [comment]
Mister Eric, Thanks for the respond firstly
And you mentioned
> (the ones included in the game's bundled textures)

Can't we just make a texture for Arabic font ?
I know Arabic faces a lot of problems regarding displaying...

Plus if you ask me the font in Android version is not that great

**Comment by efroemling** [comment]
At some point I looked into the possibility of creating textures containing all characters from all supported languages, but the amount of textures needed for this would be prohibitively large. Also some languages/fonts draw characters differently when they are arranged in certain ways, (for example, something like 'a' followed by 'e' might draw as 'æ') so I find its best to let the OS do the drawing so special cases like this are handled (as well as things like Emoji which are always evolving as new ones are added/etc).

What I hope to do is improve the 'real' font rendering so that it works everywhere and then maybe find a nice set of fonts to include with the game. Then we won't need the texture-based fonts at all and all languages will be on equal ground.

If/when we get to that point, maybe you can help pick an Arabic font that looks good?.. I'm just using whatever the default is on Android so I'm not surprised that it doesn't look amazing.

**Comment by krahma9990** [comment]
Will do Mister Eric, Will do.

**And Thanks for the quick respond**
