### ISSUE TITLE
.ktx problem

### ISSUE THREAD

**Issue by Dymkar** [efroemling/ballistica#373]
Hi Eric, I recently completed work on my modpack and decided to port it to Android, but there is a special texture format .ktx and I don't know how to edit it and import it into the game correctly. Please help me. :(

**Comment by Freaku17** [comment]
Hmm I think you know what's the textures format right? For PC platforms it's .dds and for Android it's .ktx format (as far as I know, it's different because they provide fast speed according to the platform) and for your prob,

I suppose you made it on PC and didn't edit any texture stuff. Then just download bombsquad apk from one of the test builds (https://files.ballistica.net/bombsquad/builds/old) and change it's format from .apk to .zip and extract it, then copy all the .ktx textures.

But incase you made your own .dds textures then just Google a converter .dds to .ktx and convert it, easy as that. (For my case in the past, I had to convert it from .dds to .png and then to .ktx)

**Comment by DblMKAP** [comment]
> Hmm I think you know what's the textures format right? For PC platforms it's .dds and for Android it's .ktx format (as far as I know, it's different because they provide fast speed according to the platform) and for your prob,
> 
> I suppose you made the modpack on PC and didn't edit any texture stuff. Then just download bombsquad apk from one of the test builds (https://files.ballistica.net/bombsquad/builds/) and change it's format from .apk to .zip and extract it, then copy all the .ktx textures.
> 
> But incase you made your own .dds textures then just Google a converter .dds to .ktx and convert it, easy as that. (For my case in the past, I had to convert it from .dds to .png and then to .ktx)

Where i found this convertrer? I searched all google but i have no results.

**Comment by Freaku17** [comment]
I don't remember now, but it was some program to convert to Khronos texture. Keep trying you may find it :)

**Comment by DblMKAP** [comment]
> I don't remember now, but it was some program to convert to Khronos texture. Keep trying you may find it :)

I found this program (PowerVRTexTool) but after I moved the modified texture, on android device my modpack gave an error.

**Comment by woonz70** [comment]
Download Mali Texture Compression Tool @DblMKAP
