### ISSUE TITLE
Spam in Console

### ISSUE THREAD

**Issue by vishal332008** [efroemling/ballistica#461]
This spam is going on in the console every time i open the game in my laptop.

![IMG_20220708_235745_891](https://user-images.githubusercontent.com/76160371/178050297-06419502-b4bc-48df-b4bf-32ec4ff71ac3.jpg)

I hope you will fix it , I don't know what causes this error.

And for the 2nd bug , I created a Pull Request for reverting the changes : #460 

Just one more thing , I wanted to ask about the storage permissions. Is the storage access completely removed or is it temporarily disabled due to "increased security features" and will be back in the future versions? I am asking because there are other ways we can use storage other then just plugins.

**Comment by efroemling** [comment]
I added all these logs recently while trying to track down [this bug](https://github.com/efroemling/ballistica/issues/418).

Clearly they're just annoying spam for most people (especially in debug builds which tend to run slower) so I went ahead and disabled them all in a commit I just pushed: fa3db1e3cafa451e42fdeb0230e4baac7a200838
Let me know if you are still seeing any of them.

**Comment by efroemling** [comment]
> Just one more thing , I wanted to ask about the storage permissions. Is the storage access completely removed or is it temporarily disabled due to "increased security features" and will be back in the future versions? I am asking because there are other ways we can use storage other then just plugins.

The app used to use the [READ_EXTERNAL_STORAGE](https://developer.android.com/reference/android/Manifest.permission#READ_EXTERNAL_STORAGE) permission which would let the app access the 'BombSquad' folder on shared storage. However in newer versions of Android this sort of access is either disallowed or only allowed in a limited way that is useless for the game. 

So now, on any version of Android, the game uses [Context.getExternalFilesDir()](https://developer.android.com/reference/android/content/Context#getExternalFilesDir(java.lang.String)) instead of trying to access the 'BombSquad' folder. This is a folder specific to the app which is *always* readable without asking for a permission. The downside, however, is that it is blown away if the app is uninstalled. But it's really the only option that will work consistently. I still need to update the 'Show Mods Folder' to properly show the location of this folder however.

I hope that makes sense?... So all versions of the game should still have the same full access to a mods folder that they had before; it's just no longer the 'BombSquad' folder at the external storage root.

**Comment by efroemling** [comment]
Ok I just pushed new [test builds](https://ballistica.net/builds) (buildnum 20643). I tweaked the Android version to print a clearer location when you press the 'Show Mods Folder' button. That folder is also now called 'mods' instead of 'BombSquad' (since it lives under a folder with bombsquad in the name that would be a bit redundant). Can you give it a try and let me know if there is anything that doesn't work as expected for you? Again, it should behave just how it used to except instead of its path being simply 'BombSquad' it should be something like 'Android/data/net.froemling.bombsquad/files/mods'

**Comment by vishal332008** [comment]
> Ok I just pushed new [test builds](https://ballistica.net/builds) (buildnum 20643). I tweaked the Android version to print a clearer location when you press the 'Show Mods Folder' button. That folder is also now called 'mods' instead of 'BombSquad' (since it lives under a folder with bombsquad in the name that would be a bit redundant). Can you give it a try and let me know if there is anything that doesn't work as expected for you? Again, it should behave just how it used to except instead of its path being simply `BombSquad` it should be something like `Android/data/net.froemling.bombsquad/files/mods`

I will definitely check it out and reply.

**Comment by vishal332008** [comment]
Sorry for the late reply, I was checking about the replay files and stuff.

The mods folder is working , I have tested it. 

And I was wondering if you can create a replays folder where you can add external replays. I was going to add the code into the pr where you can save a replay and load a replay but I only tested it in pc and it worked , then I found out that android storage permissions were gone. So that's why I asked about the storage permissions. 

If you can create a replays folder , then players can save their replays using the save button , those can be shared with everyone , and the replays that are shared by others can be loaded using the load button.
