### ISSUE TITLE
Update Ballistica Website

### ISSUE THREAD

**Issue by vishal332008** [efroemling/ballistica#466]
In Workspaces , there is an option called "Add Files/Folder" but there is no option named as add folder , only files and packages (which act like folders) can be added. 
So , if you can rename folders as packages , it would make more sense.

And inside workspaces , the title text has a span tag code in it , I hope you can remove that.

**Comment by efroemling** [comment]
I had a simple Folder option but I changed it to 'Package' which is simply a folder with a __init__.py in it. Since everything is Python scripts right now it didn't seem like there'd be a need for an empty non-package folder. Do you think there would be?

And can you point out where you are seeing the span tag code?

**Comment by vishal332008** [comment]
If matters , like , I have seen a lot of mods use folders to save information and things (in jsons , etc) , but as you only allowed .py files to be in the workspaces , I think there is no use of adding folders again.

The span tag is visible :
1. inside the workspace folder (where all the files and stuff are there)
2. when you select a plugin/folder
3. the add files/folders page

**Comment by efroemling** [comment]
For the moment if someone needs a folder that isn't a Python package, its not too hard to create a package and just delete its __init__.py file. I've already gotten questions about why Python scripts inside a plain folder don't work so I'd rather have people use the package option and have things work out-of-the-box in most cases.

I do want to support some other file types like README files or .json files; perhaps there should just be a hard-coded list of allowed file types/extensions 🤔

**Comment by vishal332008** [comment]
> Are you referring to the faded '(workspace)' text? That is just describing the selected item. Or am I missing something? 

Top left corner , those title tags.
![Workspace 1 _span class=_faded__(workspace)_span_ - Personal - Microsoft​ Edge 11-07-2022 21_01_20](https://user-images.githubusercontent.com/76160371/178301318-5b699128-287d-4d51-8a74-ddd7baeed015.png)
![Workspace 1 _span class=_faded__(workspace)_span_ - Personal - Microsoft​ Edge 11-07-2022 21_01_59](https://user-images.githubusercontent.com/76160371/178301356-3044b6f9-f17a-48ea-81a9-8ff28754aa44.png)
![Workspace 1 _span class=_faded__(workspace)_span_ - Personal - Microsoft​ Edge 11-07-2022 21_01_39](https://user-images.githubusercontent.com/76160371/178301401-3c4edc26-9552-40a1-9908-87efca670de8.png)

**Comment by vishal332008** [comment]
> I guess it's about <title> tag. 

Yup , those extra text "<span class="faded">(workspace)<span>" should be removed.

**Comment by efroemling** [comment]
Ok; I put those there just to describe what type thing is selected. (So, for example, if someone wonders why they don't see a 'Workspace Settings' option they might notice that it is because they have a file selected and not the workspace, etc.)

But maybe that's unnecessary, especially if it looks to people like an html error 😅. I just turned them off so let's see how that feels..

**Comment by imayushsaini** [comment]
Hey @efroemling what happened to [ballistica-web (Angular)](https://github.com/efroemling/ballistica-web) project .
I am interested to know backside story why you switched to simple html/css over Angular framework .is it because to make it light weight or you just out of time to spend time in web .
just curious 🤔.

**Comment by efroemling** [comment]
> Hey @efroemling what happened to [ballistica-web (Angular)](https://github.com/efroemling/ballistica-web) project .
> I am interested to know backside story why you switched to simple html/css over Angular framework .is it because to make it light weight or you just out of time to spend time in web .
> just curious 🤔.

The Angular project is still around, but I sidelined it for the moment just to avoid delaying 1.7 any more 😬.
Basically right now the ballistica.net website is really brain-dead html on the front-end but its a pretty decent clean Python setup on the back-end. So It works for now, but at some point I'd love to get the Angular thing going (or something equivalent). That part can be all open-sourced so people can make their own front-end modifications as long as they keep the same communication protocols in place talking to the back-end.

The setup I was working on is still live at https://console.ballistica.net and the source is at https://github.com/efroemling/ballistica-web if anyone wants to play with it. It's little more than a slightly modified angular docs page as seen at https://angular.io/docs
