### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by vishal332008** [efroemling/ballistica#467]
You can update the "Frequently Asked Questions" , such as "Q: Will my existing BombSquad 1.4.x mods still work?" which still refers to 1.4 but the process has been made till 1.7 now. So updating the README might be useful. And as you have the full knowledge about the updates and new features such as v2 accounts that you have made in 1.7, you can easily give answer about the features and compatibility of devices in the questions.

**Comment by Dliwk** [comment]
I think whole README should be updated sometime. While it still have some relevant topics in project goals and FAQ, some time has passed too and its focus may be shifted from '1.4 vs 1.5 difference' to 'what's this at all?' (but these articles can be moved to some wiki page, for some future historical purposes); now most of people coming here most likely for the first time they encounter BombSquad than people played/modded 1.4 before. I also think we can discuss here topics that should be covered in updated README.

Just for example, there definitely should be link to 'coming-right-after-1.7 official discord server' and direct link to 'also-coming-right-after-1.7 Python API documentation'. :))

**Comment by efroemling** [comment]
I agree this stuff needs updating. And yes fixing the docs page and the discord server. 😬.  I'm currently rewriting some Google Play integration stuff to use different newer libraries (as required by Google as of a few months ago) which should be the last thing I need to do for the Google Play 1.7 build. I'll be doing a slow roll-out of that version since there's so many changes (and since it's most of my income hehe) ..so while that rollout is happening I should have some time to tackle all this other stuff before I start moving on to 1.8.

**Comment by vishal332008** [comment]
I know you will fix it soon but I can see that it is going to take some time so I am going ahead and closing this issue for now.
