### ISSUE TITLE
Mods in ba_root/mods are not being executed

### ISSUE THREAD

**Issue by Awesome-Logic** [efroemling/ballistica#48]
Well the title is self explanatory. Looks like the mods folder is not properly wired up.

**Comment by efroemling** [comment]
This is somewhat by design. 1.4 would simply import every script it found in the game's various python directories (such as the mods dir). However this isn't a very good idea for a number of reasons. For 1.5 I moved to a tagging system where scripts can tag things that they provide and the game can use those tags to locate and import particular modules such as mini-games dynamically.

https://github.com/efroemling/ballistica/wiki/Meta-Tag-System

The only issue is that there is not yet a way to tag something that wants to run at game launch or other particular times. I'll try to get this added in as soon as I can, but for right now you may have to add explicit imports for mod scripts that you add. The stuff in mods should still be importable; it's just not getting imported by default.

ba._app.on_app_launch() would probably be the correct place to add any extra imports/etc that you wanted. It wouldn't be too hard to wire it up to scan the mods dir and import everything it finds there if you want to restore the old behavior.

**Comment by efroemling** [comment]
We could also add an opt-in "Import Everything In Mods Folder" option in settings/advanced for the time being until there's an official meta-tag for stuff wanting to run at launch...

**Comment by Dliwk** [comment]
Hmm, but what about new meta-tag like `# ba_meta import requied`? It will not lead to the import of older mods.

**Comment by efroemling** [comment]
For the record, yes I am planning to add a meta-tag to register 'plugins' that get executed on launch. I'll try to get this in within the next few days.
