### ISSUE TITLE
Gplay V2 multi account handling issue

### ISSUE THREAD

**Issue by imayushsaini** [efroemling/ballistica#548]
### Description
Managing multiple accounts with a google play login is difficult now and kinda buggy.

Previously we could just press logout and during log in it ask for an account to use(gplay dialogue).
Now even with re login it just signin with previous account, no prompt for account choice.

Then I found setting in google play games app , and set bombsquad to "ask each time".
Maybe it was picking default account only . But now issue is everytime I launch game it asks for account to use , moreover even if I select some account(other account) then still game is signed in with previous signed account.
It only change if I signout and then press login.

### Steps to reproduce
1. Launch Game login with google play account 'X' and exit.
2. Launch Google PlayGames and change account setting to "ask each time".
3. Launch game (it will ask account to use on launch only)
4. Select account 'Y' 
5. Wooh. Game still logged in with account 'X'.
6. Press logout
7. Press login , (it will signin to account 'Y').

### Expected behavior
It should not ask account on every game launch.
It should ask account at step 7.

**Comment by efroemling** [comment]
Unfortunately I don't think this is something I have control of (anymore).
As part of this update I've also updated the Google Play Game Services library from the crazy-old version I was using to the latest ones. One of the features of the newest one is that is handles signing you in automatically and doesn't provide a way to sign out.

<img width="920" alt="Screenshot 2022-11-19 at 11 32 03 AM" src="https://user-images.githubusercontent.com/10857610/202868257-4c6ddd14-3523-4fee-87fd-3c4751708353.png">

full docs: https://developers.google.com/games/services/android/signin

In a way this is nice in that it makes it easier to integrate the library, but it's a bummer to not be able to sign out. So I've added an abstraction later (see ba._login.LoginAdapter) which lets us technically sign out by 'disconnecting' from the still-logged-in GPGS state. But if you sign in again then you are back with that same GPGS login.

Since Google no longer provides a way to sign-out from within the app, I'm guessing they want users to do so from system settings or something like that. Perhaps we could add a note in the game somewhere letting people know that's what they need to do if they want to switch GPGS accounts. (maybe when they sign-back in via the GPGS button?)

Curious if you have any thoughts on how to better handle this.

**Comment by efroemling** [comment]
Thinking about this more, we should definitely be able to get the 'ask each time' + switching-accounts case to work as expected. The only thing that is probably technically impossible is signing out from the game and signing back in with a different GPlay account (since the library no longer supports signing out as I mentioned above). But we can mention to the player that they need to restart the app if they want to switch accounts. I'll make some of these changes and post an update and see what you folks think...
