### ISSUE TITLE
Game progress is gone

### ISSUE THREAD

**Issue by LogExE** [efroemling/ballistica#555]
### Description
Game doesn't seem to remember what stuff i've unlocked before (characters, maps,...), the only thing is still there is my game achievements, but all the other stuff on my save is gone. Even bombsquad pro (which i have bought previously) tells me to buy it. 

### Steps to reproduce
1. Launch BombSquad
2. Go to store
3. See everything is locked, even bombsquad pro

### Expected behavior
Game should allow me to use my unlocked items

### Machine
**Platform**: Android 11
**BombSquad version**: 1.7.17

### Extra
I had the exact same problem in the past and had solved it by resetting game in Google Play Games app, but it doesn't work as for now.

**Comment by kingsamurai123** [comment]
Do you still experience this issue?

**Comment by LogExE** [comment]
I do

**Comment by kingsamurai123** [comment]
Are you logging in with the same google play account? I think from 1.7.17, by default the game should create a v2 account and sync your profile to that account. But losing the data is unheard of and since you are still unable to retrieve the account, try joining the official discord server and see if anyone can assist you. 

In addition, if you don't mind starting the game fresh. You can send an email to eric with your bs pro transaction id, the old account related information and a new account which you want to transition to.

**Comment by LogExE** [comment]
Yes, the same account I used previously. I was told to fill github issue ticket on discord server, nothing else

**Comment by Dliwk** [comment]
Sorry for long response; if you still experience this issue, email support@froemling.net.
