### ISSUE TITLE
Error: Plugin Settings Checkbox "maxwidth"

### ISSUE THREAD

**Issue by JoseANG3L** [efroemling/ballistica#562]
### Description
Find an error in the text length in the checkbox, in other languages the text goes out of the window, the correct maxwidth attribute would be **"maxwidth=308"**.

File address: bastd/ui/settings/pluginsettings.py
Code line: 111

```
self._enable_new_plugins_check_box` = ba.checkboxwidget(
            parent=self._root_widget,
            position=(65, self._y_position),
            size=(350, 60),
            value=ba.app.config.get(
                ba.app.plugins.AUTO_ENABLE_NEW_PLUGINS_CONFIG_KEY,
                ba.app.plugins.AUTO_ENABLE_NEW_PLUGINS_DEFAULT,
            ),
            text=ba.Lstr(resource='pluginsAutoEnableNewText'),
            scale=1.0,
            maxwidth=308,
            on_value_change_call=self._update_value,
        `)
```
### Screenshots
Before
![old](https://user-images.githubusercontent.com/57434391/213897664-6b528264-ecf1-436d-b890-66471a81f9ab.jpg)
After
![new](https://user-images.githubusercontent.com/57434391/213897662-dda3d080-e34f-4b06-9618-de614096d741.jpg)

**Comment by efroemling** [comment]
Good catch; thanks! Just pushed a fix: 2d3430817af4662f2581511acc69132a40d33c1c

As a side note to anyone reading this: due to some stupid scaling math, the 'maxwidth' values on text widgets are not always intuitive and its best to just test them and see what looks good. When I'm building UIs I generally temporarily replace text with something like 'blah blah blah blah blah blah blah blah blah blah blah' just to make sure max width kicks in so I can make sure its set to a good value.
