### ISSUE TITLE
ba.animate giving error

### ISSUE THREAD

**Issue by rahulraman0108** [efroemling/ballistica#57]
The ba.animate gives RuntimeError when trying to animate the text node's scale property inside handlemessage function.

![image](https://user-images.githubusercontent.com/42905362/84762478-7a754280-afe8-11ea-8e43-905f83be6e6e.png)

![image](https://user-images.githubusercontent.com/42905362/84762528-89f48b80-afe8-11ea-8713-ddafc9590025.png)

**Comment by rahulraman0108** [comment]
**Update**
Fixed the error by creating a 1ms delay timed call and it works.
However, I yet want to know what was the reason it did not work that way and why did this happen.
The updated code I used is in the image below:

![image](https://user-images.githubusercontent.com/42905362/84872153-25483800-b09f-11ea-862c-d52c6e96554c.png)

**Comment by efroemling** [comment]
This is a new error that I added recently; 1.4 used to allow such code to run although it was technically unsafe. Basically what is happening is that certain callbacks such as ba.DroppedMessage run in the middle of the scene simulation step, and at that time it is unsafe to create or destroy nodes or otherwise modify the scene or it can lead to crashes. And ba.animate() creates and modifies nodes.

Using a timer like you have done or simply using ba.pushcall() to run something in the next loop cycle is the correct workaround here. 👍🏻

In the future I will probably change those callbacks to happen after the simulation step so that such workarounds are unnecessary, but I didn't want to do that now just in case it subtly breaks any game logic. (Don't want to delay 1.5 any more than I already have)

**Comment by efroemling** [comment]
I'll go ahead and close this. Let me know if you have any more questions about this...
