### ISSUE TITLE
Segfault in "Local Network" tab

### ISSUE THREAD

**Issue by Dliwk** [efroemling/ballistica#60]
Recently I ran into following problem: when I open the local network tab in the Gather window, I always get segfault in **ballistica::Platform::GetBroadcastAddrs()** (**bombsquad::Platform::GetBroadcastAddrs()** in 1.4) at platform.cc:1182. I don't know what I changed at my system, but everything worked before.

**Comment by efroemling** [comment]
Ok I think I fixed this in commit baac8eb48946c9d5c47f1035947f24ee8c9f9c07.
Can you try it and see if it works for you now?
For the record, I believe the issue was [this](https://stackoverflow.com/questions/22767155/when-will-ifa-addr-be-null-on-calling-getifaddrs) (a null pointer when a network interface has no addresses that I was not handling)

**Comment by Dliwk** [comment]
Ok now it works fine.
