### ISSUE TITLE
Startup error BombSquad 1.5.9 on Windows

### ISSUE THREAD

**Issue by KoLenka12** [efroemling/ballistica#67]
I have a 32-bit windows system. And when I start the system gives me an error:
(version this file don't incompatible with using version Windows. Use the system information to determine the version of the program (32-bit or 64-bit) and contact the publisher of the Software.)
![unknown](https://user-images.githubusercontent.com/58659520/85555846-f990f900-b62e-11ea-9d7e-90d0cebcfb36.png)

**Comment by KoLenka12** [comment]
Now i tried to run BombSquad 1.5.11 on my 32-bit Windows. Throws the same error:
![Снимок](https://user-images.githubusercontent.com/58659520/85558265-41b11b00-b631-11ea-86e7-e1ffcf0eebf8.PNG)

**Comment by efroemling** [comment]
Thanks for the heads-up. I switched all builds from 32 bit to 64 bit for 1.5 because I thought most everyone would be running 64 bit windows these days. But apparently that's not the case yet :).
I'll switch the builds back to 32 bit soon.. (though perhaps I will still provide a 64 bit option for those who want it).

**Comment by efroemling** [comment]
Ok, the latest commit changes the prefab binaries to 32 bit: 9a12f02689e3cc1793dbe6fcfe679303822fec48
Can I have you try the latest stuff and let me know if it works for you? (preferably both the debug and release builds if you could)

**Comment by efroemling** [comment]
I'll go ahead and close this. Please open a new issue if anything is still not working.
