### ISSUE TITLE
Language remaining unchanged after language is changed

### ISSUE THREAD

**Issue by Benefit-Zebra** [efroemling/ballistica#76]
The dafault language of BombSquad is English. When I change the language to any other, go to Main Menu, tap on play button, tap on Team, and then again change the language to English and go to Teams Section/FFA section, the language of the second and third playlist remain unchanged as you can see:

![IMG-20200626-WA0010](https://user-images.githubusercontent.com/42458260/85915095-46a8e100-b862-11ea-893d-d4f654e1d73b.jpg)
![IMG-20200626-WA0011](https://user-images.githubusercontent.com/42458260/85915096-47da0e00-b862-11ea-8a21-342a54810392.jpg)

**Comment by efroemling** [comment]
This is expected behavior actually. The default playlist is 'special' in that its real name is __default__ and it always shows up in the current language, but when the game first launches it creates a few other regular playlists which aren't special. Regular playlists don't have their names translated so it has to 'hard code' their names to whatever the language was at launch.

Perhaps this could be made more elegant but for now it's expected..

**Comment by Sachin247c** [comment]
@efroemling gotcha ! 😅
