### ISSUE TITLE
Date data 

### ISSUE THREAD

**Issue by Sachin247c** [efroemling/ballistica#77]
i know this may be a weird idea  but still , 
i am actually assuming that if you have any kind of data of an account by which you can identify ones account connected to bombsquad at which date ,
in short that would be great if you can just add a time stamp for every player's id that on which date that guy i'd was made or connected to bombsquad .....
and this kind of data can even be useful in some scenarios where many windows / linux players just deletes there bs i'd ( linux**** , PC******* ... like that ) and just joins with some new i'Ds and some times it gets super annoying , that even when you kick somebody  
just comes back like nothing happened
 btw if that cloning thing is not possible , but a request just to make that date of joining a real thing .. that would be great to know for how long i have been playing bombsquad :)

**Comment by efroemling** [comment]
I do have this data for all accounts. I'll try to make this viewable or otherwise available to server owners or possibly in the standard account view UIs at some point. My current plan is to include this in the remaining refactoring that I'll be doing for [1.8](https://github.com/efroemling/ballistica/wiki/Roadmap#ballistica-18).

**Comment by Sachin247c** [comment]
Great , the game's future is damn good!!

**Comment by efroemling** [comment]
Gonna close this for now to keep the issues section manageable, but please bring it up again around 1.8 if I haven't gotten it in there yet...
