### ISSUE TITLE
Can you please keep the power boxes fixed in certain areas?

### ISSUE THREAD

**Issue by astrojade** [efroemling/ballistica#82]
The power boxes are always spawning over the players head, either they disrupt the game by just falling over you and self detonating or just coming in the way of a throw, and changing the direction of the bomb. Please do something about this.

**Comment by Benefit-Zebra** [comment]
@astrojade Are you talking about **Powerup Box** or **TNT Box**?

**Comment by astrojade** [comment]
> @astrojade Are you talking about **Powerup Box** or **TNT Box**?

Not the tnt box, That is always fixed in one place. The problem is with the remaining power boxes. They spawn right over your head and its really bad while playing tournaments.

**Comment by Benefit-Zebra** [comment]
@astrojade Does this happen on every map?

**Comment by Benefit-Zebra** [comment]
@astrojade Does this happen on every map?  Can you please share a video of this?

**Comment by efroemling** [comment]
Any other folks have thoughts on this? I've heard this mentioned before as a complaint. If its a problem on specific maps/spawn-points perhaps we can just move the spawn areas down so they're not above people's heads. Or perhaps powerup spawning can be made smarter to happen slightly away from any players hanging out under the spawn area...

**Comment by Benefit-Zebra** [comment]
@efroemling I have thought on this. Sometimes when I play game, powerups spawn at level of head, causing little damage and we take the powerup.

The problem is if the powerup happens to be Curse, we unwillingly take the powerup because it spawned there.

Also when we are playing with bot, it a powerup spawns at the bot head, it also gets little damage like spaz.

**Comment by astrojade** [comment]
Problem is that, even if you put it a few centimetres away from the player, if the player is throwing a bomb and it immediately pops up from top, at the correct time, the player would self detonate. Can you do something about this, I mean it really gets annoying to the point of self destruction.

**Comment by efroemling** [comment]
What if we simply make it so that powerup boxes don't collide with *anything* until after they hit the floor?

This way if a powerup spawns above you, it will fall through you and hit the floor, and if you want to get it you will have to move away from it and then move back onto it.

There will probably still be cases where a powerup box would fall randomly, hit the floor, and then interfere with a thrown bomb, but I doubt we can 100% prevent that unless we made the boxes completely non-physical. (and I think a tiny bit of such random luck can be good).

Thoughts?

**Comment by Benefit-Zebra** [comment]
Yeah, this will be a good idea.

**Comment by astrojade** [comment]
Yup, i agree, this is a great idea
