### ISSUE TITLE
Mine Blast

### ISSUE THREAD

**Issue by Sachin247c** [efroemling/ballistica#90]
I know this thing now for quite a time , but don't know if that was a bug or you did that purposely , 
Thing is when we blast a mine at any kind of power up box , due to blast that power up do not disappears , while any kind of other blast ( TNT , sticky , etc ) does so ... 
If you want any type of better explanation i can provide that too.. but hope you understand..
Nutshell - Mine blast do not affects powerups!

**Comment by Benefit-Zebra** [comment]
@Sachin247c Contradictory to what you said, I tested if mine blast disappears powerup box or not, Powerup box near mine blast do get disappear.

Nutshell - Mine blast do affects powerup boxes!

**Comment by Sachin247c** [comment]
In my case is did not actually! And i tried this 10+ times! Just to get sure ( but wait a min. I tried all that in LAST STAND ) you can check that too in LAST STAND and let me now .. until i am checking that in another levels ;)

**Comment by Sachin247c** [comment]
So i have checked that thing in all types of games ! ( Co - ops , ffa , teams , epics , unepics ) the thing remains same ;/ oof

**Comment by efroemling** [comment]
Unless I am forgetting something, all explosions should destroy powerup boxes, so if they aren't in some cases then we should fix that.
If you'd like to look into it, it shouldn't be too tricky. Just throw some print statements in to see what is happening or not happening.
Basically, any type of bomb going off should create a Blast (bastd.actor.bomb.Blast) which receives an ExplodeHitMessage when it touches most things. It then sends a HitMessage to things that it touched. Powerup boxes (bastd.actor.powerupbox.PowerupBox) should respond to HitMessages by killing themselves.

**Comment by Sachin247c** [comment]
@efroemling yeah , but the main thing is i don't know even this much of python! (oooof) all i can help now is catching some bugs !....

**Comment by efroemling** [comment]
No worries! I can try to take a look at this when I have time, though I'm in the middle of squishing the remaining 1.5 bugs right now so I can't say when I'll get to it.

**Comment by Benefit-Zebra** [comment]
@efroemling @Sachin247

[Landmine Test Viseo](https://drive.google.com/file/d/1niEOVgcqB6iGIkQEnoidTI3ubxs5ig99/view?usp=drivesdk)

**Comment by Sachin247c** [comment]
https://drive.google.com/file/d/1-0uTA0fUU6IcwVAuE4mt325HL8UrL2LM/view?usp=drivesdk 

Check this out

**Comment by Benefit-Zebra** [comment]
@Sachin247c  Your file is asking to request access check if the link sharing option is on.

**Comment by Sachin247c** [comment]
Done @Benefit-Zebra

**Comment by Zee-hash** [comment]
We always use throwing mine + punching the mine to achieve it. . it's just an advanced skill for us. It will be harmful to players but powerups.

**Comment by Benefit-Zebra** [comment]
@Sachin247c I got the problem.

Landmines, by default get the hittype by which they explode. Since in this case, you throw and punch the landmine, landmine gets the hittype 'punch'. The code is written in powerup.py in such a way that if the hittype is any other than punch, the powerup gets disappear.

Now its on @efroemling if he wants to remove ```python hittype != punch ``` or not.

**Comment by Sachin247c** [comment]
@Benefit-Zebra  thats what i said in my first comment " purposely " just wanted to remind him if he did that purposely or it is actually a mistake!... :')

**Comment by Zee-hash** [comment]
I recorded a video to show this. https://youtu.be/fM0OHTV1DLo, if you don't have enough time, you can watch it from 01:10.

**Comment by Benefit-Zebra** [comment]
@Zee-hash There was no need to make a video and upload it to Youtube. Then too, Thanks very much. I have gotten the issue. :+1:

**Comment by PizzaSlayer64** [comment]
This indeed only occurs when the landmine is punched.
This may happen because of how the landmine handles hits; it "inherits" the hit type of what triggered it in the first place.
**[Line 1024-1026 @ bastd/actor/bomb.py]**

Meaning that this _might_ be done on purpose, and could be the same when punching impact bombs.

**Comment by efroemling** [comment]
Hey folks; thanks for looking into this. I accepted the PR but added some modifications on top of it. The logic I had in there before was flawed in that it was theoretically possible for a single bomb to generate multiple explosions if hit by multiple things at basically the same time. This should be fixed now.

Also, I removed the logic that caused bombs to inherit the hit-type of what set them off. I don't remember the exact reason I originally put that in there; inheriting the source-player/etc. of something that sets off a bomb makes sense but not inheriting hit-type. A land-mine should not suddenly behave like a punch just because a punch set it off, etc. 🤔

Anyway, holler if any of you notice any odd behavior due to these changes... I'll leave this thread open for discussion and close it soon if there are no issues.

**Comment by Sachin247c** [comment]
@efroemling so , in version 1.5.18 its not still fixed :/

**Comment by efroemling** [comment]
Those changes have been pushed to the ballistica repo here but I haven't yet spun off new BombSquad builds. That should show up in 1.5.19 which I'll probably push out later tonight or tomorrow.

**Comment by efroemling** [comment]
Just a note that 1.5.19 is out in all test builds now as well as here in the ballistica repo. Anyone continuing to see any odd behavior?

**Comment by Sachin247c** [comment]
Everything seems ok to me , and yeah ... That mine in now destroying powerups ;)

**Comment by Benefit-Zebra** [comment]
Everything seems normal and fine.

**Comment by TornadoesPride** [comment]
@efroemling rest assure as this bug is not becoz of the 1.5 update, this bug has been over the previous updates, the only reason(for me!) I didn't report cuz its quite useful... but yea even if you dont resolve this the game is working as awesome as ever

**Comment by efroemling** [comment]
Ok it sounds like we're good here 👍
I'll go ahead and close this but please holler if anything similar is still occurring...
