### ISSUE TITLE
gravityScale is absent

### ISSUE THREAD

**Issue by Benefit-Zebra** [efroemling/ballistica#92]
I wanted to use gravityScale option in my mods, so
I was searching for the gravityScale option in **_ba.py**, but it was nowhere to be found, nor it is in **ba** docs.

**Comment by efroemling** [comment]
Ok, I just pushed a commit with gravity_scale as a ba.Node attribute in _ba.py.
Currently node attributes don't interact with the type checker very cleanly. Under the hood, different node types have different attributes, but in Python's eyes there is a single ba.Node type, so I'm currently just adding all possible attributes to it manually in the dummy _ba module to keep the type checker happy. If you see any others that I missed (like gravity_scale), let me know or submit a PR with it added to the dummy _ba.py.

In the future (hopefully version [1.8](https://github.com/efroemling/ballistica/wiki/Roadmap#ballistica-18)) I plan to make things smarter so that there is a proper Python type generated for each different node type so it'll be much easier to see which attributes are available and no attributes will be accidentally left out.
