### ISSUE TITLE
Weird Behaviour of Spaz on Landmine

### ISSUE THREAD

**Issue by Benefit-Zebra** [efroemling/ballistica#95]
When I was writing mods, I forgot to arm the landmine. When I played the mod, I found a bug. 

When I land on landmine, the behaviour of spaz is of falling. The spaz should instead be standing on landmine.

Also few landmine **got inside the map**. 

This Bug is so unexplainable, you can understand that by seeing the video.

[Landmine Bug Video](https://drive.google.com/file/d/1qN-DPEwAECHejwSWzzqBzqhQTQleAbqU/view?usp=drivesdk)

_The same happens when a Bot spawns on a powerup box_. As the bot can't take powerup, his behaviour is also of falling like spaz. And when a player jumps and lands on Puck.

**Comment by efroemling** [comment]
It might seem strange, but everything here is expected behavior.

- Certain objects convey 'footing', which means that the spaz will keep itself upright while it is touching them. Mostly only terrain objects do this, but I think TNT boxes also might. If bombs/mines did, however, then a spaz flying through the air while holding on to one of them would stay upright which would look wrong. So that's why he looks drunk when he tries to walk on a non-exploding mine; he has no 'footing'. Perhaps this system can be made smarter in the future but that's how it works for now.

- The mines falling through the floor is also unsurprising. Mines are simulated as very thin boxes and terrain objects are simulated as infinitely thin polygons.. things are simulated in 'steps' so if a mine is falling fast enough there is a good chance it will completely (or mostly) pass through the polygon in one step and never register a collision. Perhaps this system can be improved in the future, but for now I would suggest trying to not let mines fall completely flat or not from as high up.

Hope that helps!
